# Projekt Informationen
site_name: Dokumentation
site_author: Johann Friedrich Heuer
site_description: Dokumentation für die Informatik AG am Kaiser-Wilhelm- und Ratsgymnasium Hannover 

# Repository
repo_name: GitHub Repository
repo_url: https://github.com/kwr-informatik-ag/documentation

# Copyright
# copyright: Copyright &copy; 2024 KWR Hannover

theme:
  name: material
  features:
    - toc.follow
    #- toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - search.suggest
  language: de
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  favicon: assets/favicon.png
  logo: assets/images/logo-full.png

extra:
  homepage: https://kwr-informatik-ag.github.io/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kwr-informatik-ag/

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - social
  - search

nav:
  - Hauptseite: https://kwr-informatik-ag.github.io/
  - Startseite: index.md
  - Server: server/index.md
  - Projekte:
    - projekte/index.md
    - Werwolf Webapp: projekte/werwolf-webapp/index.md
