site_name: KWR Informatik AG Documentation
theme:
  name: material
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
  language: en
nav:
  - Welcome: index.md

  - Devops (WIP):
    - "Home": devops/index.md
    - Git:
      - "What is Git": devops/git/index.md
  
  - Languages (WIP):
    - "Home": languages/index.md
    - Web:
      - HTML:
        - "Introduction": languages/html/index.md
      - CSS:
        - "Introduction": languages/css/index.md
      - Javascript:
        - "Introduction": languages/javascript/index.md
      - Typescript:
        - "Introduction": languages/typescript/index.md
    #- Python: # Free-For-All to extend on
    #  - "Introduction": languages/python/index.md
    #- C: # Free-For-All to extend on
    #  - "Introduction": languages/javascript/index.md
    #- C#: # Free-For-All to extend on
    #  - "Introduction": languages/javascript/index.md
    #- C++: # Free-For-All to extend on
    #  - "Introduction": languages/javascript/index.md
    #- Java: # Free-For-All to extend on
    #  - "Introduction": languages/java/index.md


  - Frontend (WIP):
    - "Home": frontend/index.md
    - Nodejs:
      - Getting Started:
        - "Quick Guide": frontend/nodejs/getting-started/quick-guide.md
        - "Installation": frontend/nodejs/getting-started/installation.md
      - Tutorial:
        - "Fundamentals": frontend/nodejs/tutorial/basics.md
    - Svelte:
      - Getting Started:
        - "Introduction": frontend/svelte/getting-started/introduction.md