site_name: KWR Informatik AG Dokumentation (In Arbeit)
theme:
  name: material
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
  language: de
nav:
  - Hauptseite: https://kwr-informatik-ag.github.io/
  - Startseite: index.md