site_name: KWR Informatik AG Documentation
theme:
  name: material
  features:
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
  language: de
nav:
  - Willkommen: index.md

  - Devops (WIP):
    - "Start": devops/index.md
    - Git:
      - "Was ist Git": devops/git/index.md
  
  - Programmiersprachen (WIP):
    - "Start": languages/index.md
    - Web:
      - HTML:
        - "Einführung": languages/html/index.md
      - CSS:
        - "Einführung": languages/css/index.md
      - Javascript:
        - "Einführung": languages/javascript/index.md
      - Typescript:
        - "Einführung": languages/typescript/index.md
    #  - Python: # Free-For-All to extend on
    #    - "Einführung": languages/python/index.md
    #  - C: # Free-For-All to extend on
    #    - "Einführung": languages/javascript/index.md
    #  - C#: # Free-For-All to extend on
    #    - "Einführung": languages/javascript/index.md
    #  - C++: # Free-For-All to extend on
    #    - "Einführung": languages/javascript/index.md
    #  - Java: # Free-For-All to extend on
    #    - "Einführung": languages/java/index.md


  - Frontend (WIP):
    - "Start": frontend/index.md
    - NodeJS:
      - Erste Schritte:
        - "Schnellanleitung": frontend/nodejs/getting-started/quick-guide.md
        - "Installation": frontend/nodejs/getting-started/installation.md
      - Tutorial:
        - "Grundlagen": frontend/nodejs/tutorial/basics.md
    - Svelte:
      - Getting Started:
        - "Introduction": frontend/svelte/getting-started/introduction.md
