site_name: KWR Informatik AG Documentation
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - toc.integrate
    - toc.follow
  language: en
nav:
  - Welcome: index.md

  - Devops:
    - "Home": devops/index.md
    - Git:
      - "What is Git": devops/git/index.md
    
  - Frontend (WIP):
    - "Home": frontend/index.md
    - Nodejs:
      - Getting Started:
        - "Quick Guide": frontend/nodejs/getting-started/quick-guide.md
        - "Installation": frontend/nodejs/getting-started/installation.md
      - Tutorial:
        - "Fundamentals": frontend/nodejs/tutorial/basics.md
    - Svelte:
      - Getting Started:
        - "Introduction": frontend/svelte/getting-started/introduction.md